// Autogenerated file - DO NOT EDIT!
"set platform meta";
"addSysCall setScreenMode setFPS setPen setFont setLED setTexture";
"addSysCall setMirrored setFlipped setTransparent";
"addSysCall getWidth getHeight";
"addSysCall clear image text rect";
"push globals UP DOWN LEFT RIGHT A B C D";
"registerBuiltinResource fontMini fontTIC806x6 fontZXSpec fontAdventurer fontDonut fontDragon fontC64 fntC64UIGfx fontMonkey fontKarateka fontKoubit fontRunes fontTight fontTiny";
"include /source/main.js"
